package com.github.tkawachi

import org.apache.maven.artifact.versioning.ComparableVersion
import sbt.{ IO, File, ModuleID }
import sbt.Keys.TaskStreams

object SbtLock {

  case class Artifact(organization: String, name: String) {
    def sbtString(revision: String) =
      Seq(organization, name, revision).map("\"" + _ + "\"").mkString(" % ")
  }

  def doLock(allModules: Seq[ModuleID], outputFile: File, s: TaskStreams): Unit = {
    val revisionsMap: Map[Artifact, Map[String, Set[String]]] =
      allModules.groupBy { m =>
        Artifact(m.organization, m.name)
      }.mapValues { modulesInArtifact =>
        modulesInArtifact.groupBy(_.revision).mapValues { modulesInRevision =>
          modulesInRevision.map(_.configurations).flatten.toSet
        }
      }

    val moduleLines = revisionsMap.map {
      case (artifact, revisions) =>
        artifact.sbtString(chooseRevision(artifact, revisions, s))
    }.toSeq.sorted.mkString(",\n  ")
    val dependencyOverrides =
      "// This file is auto generated by sbt-lock.\n" +
        "// https://github.com/tkawachi/sbt-lock/\n\n" +
        "dependencyOverrides ++= Set(\n  " +
        moduleLines +
        "\n)\n"

    IO.write(outputFile, dependencyOverrides)
    s.log.info(s"$outputFile was created.")
  }

  def chooseRevision(artifact: Artifact, revisions: Map[String, Set[String]], s: TaskStreams): String = {
    if (revisions.size == 1) revisions.head._1
    else {
      s.log.info(s"Multiple versions exist for ${artifact.organization} % ${artifact.name}:")
      revisions.foreach {
        case (rev, configs) =>
          s.log.info(s"  * $rev in ${configs.mkString(",")}")
      }
      val revision = latest(revisions.keys.toSet)
      s.log.info(s"  -> $revision is chosen.")
      revision
    }
  }

  def latest(revisions: Set[String]): String = revisions.maxBy(new ComparableVersion(_))

}
